name: App request
description: Request an app on GitHub be added to Universal-DB
labels: ["app request"]
body:
  - type: markdown
    attributes:
      value: "**Please ensure your app complies with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/master/CONTRIBUTING.md#app-requests) before submitting a request.**"
  - type: markdown
    attributes:
      value: "Go to [the app request web page](https://db.universal-team.net/app-request) and fill out the form to create a JSON for submission then come back here to submit it. Note that rarely used features are currently missing from the form, see [the wiki](https://github.com/Universal-Team/db/wiki/App-Template) for more information."
  - type: markdown
    attributes:
      value: "Know how to use git? Consider submitting a pull request instead. (this is a hobby project, as simple as it is we don't have time to sit down and review everything all the time. Pull requests will be reviewed much faster)"
  - type: textarea
    attributes:
      label: Submission form
      description: Upload your JSON file here. You can also upload screenshots here.
  - type: checkboxes
    attributes:
      label: Developer permission
      description: If you aren't a developer of the app, then please actually check it's alright with them.
      options:
        - label: I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)
          required: true
